// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: game_server.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRoomByCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms []*Room `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *GetRoomByCodeResponse) Reset() {
	*x = GetRoomByCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomByCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomByCodeResponse) ProtoMessage() {}

func (x *GetRoomByCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomByCodeResponse.ProtoReflect.Descriptor instead.
func (*GetRoomByCodeResponse) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{0}
}

func (x *GetRoomByCodeResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type GetRoomByCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GetRoomByCodeRequest) Reset() {
	*x = GetRoomByCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomByCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomByCodeRequest) ProtoMessage() {}

func (x *GetRoomByCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomByCodeRequest.ProtoReflect.Descriptor instead.
func (*GetRoomByCodeRequest) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{1}
}

func (x *GetRoomByCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type PutInQueueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *PutInQueueRequest) Reset() {
	*x = PutInQueueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutInQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutInQueueRequest) ProtoMessage() {}

func (x *PutInQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutInQueueRequest.ProtoReflect.Descriptor instead.
func (*PutInQueueRequest) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{2}
}

func (x *PutInQueueRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type AddCallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId     int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	OpponentId int64 `protobuf:"varint,2,opt,name=opponent_id,json=opponentId,proto3" json:"opponent_id,omitempty"`
}

func (x *AddCallRequest) Reset() {
	*x = AddCallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCallRequest) ProtoMessage() {}

func (x *AddCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCallRequest.ProtoReflect.Descriptor instead.
func (*AddCallRequest) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{3}
}

func (x *AddCallRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *AddCallRequest) GetOpponentId() int64 {
	if x != nil {
		return x.OpponentId
	}
	return 0
}

type DeleteCallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpponentId int64 `protobuf:"varint,1,opt,name=opponent_id,json=opponentId,proto3" json:"opponent_id,omitempty"`
}

func (x *DeleteCallRequest) Reset() {
	*x = DeleteCallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCallRequest) ProtoMessage() {}

func (x *DeleteCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCallRequest.ProtoReflect.Descriptor instead.
func (*DeleteCallRequest) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCallRequest) GetOpponentId() int64 {
	if x != nil {
		return x.OpponentId
	}
	return 0
}

type SendTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId int64 `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Time   int64 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *SendTimeRequest) Reset() {
	*x = SendTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTimeRequest) ProtoMessage() {}

func (x *SendTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTimeRequest.ProtoReflect.Descriptor instead.
func (*SendTimeRequest) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{5}
}

func (x *SendTimeRequest) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *SendTimeRequest) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type GameInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpponentNickname string  `protobuf:"bytes,1,opt,name=opponent_nickname,json=opponentNickname,proto3" json:"opponent_nickname,omitempty"`
	GameId           int64   `protobuf:"varint,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Rooms            []*Room `protobuf:"bytes,3,rep,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *GameInfo) Reset() {
	*x = GameInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfo) ProtoMessage() {}

func (x *GameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfo.ProtoReflect.Descriptor instead.
func (*GameInfo) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{6}
}

func (x *GameInfo) GetOpponentNickname() string {
	if x != nil {
		return x.OpponentNickname
	}
	return ""
}

func (x *GameInfo) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GameInfo) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type StreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//	*StreamResponse_GameResult
	//	*StreamResponse_GameInfo
	Result isStreamResponse_Result `protobuf_oneof:"result"`
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{7}
}

func (m *StreamResponse) GetResult() isStreamResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *StreamResponse) GetGameResult() string {
	if x, ok := x.GetResult().(*StreamResponse_GameResult); ok {
		return x.GameResult
	}
	return ""
}

func (x *StreamResponse) GetGameInfo() *GameInfo {
	if x, ok := x.GetResult().(*StreamResponse_GameInfo); ok {
		return x.GameInfo
	}
	return nil
}

type isStreamResponse_Result interface {
	isStreamResponse_Result()
}

type StreamResponse_GameResult struct {
	GameResult string `protobuf:"bytes,1,opt,name=game_result,json=gameResult,proto3,oneof"`
}

type StreamResponse_GameInfo struct {
	GameInfo *GameInfo `protobuf:"bytes,2,opt,name=game_info,json=gameInfo,proto3,oneof"`
}

func (*StreamResponse_GameResult) isStreamResponse_Result() {}

func (*StreamResponse_GameInfo) isStreamResponse_Result() {}

var File_game_server_proto protoreflect.FileDescriptor

var file_game_server_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x75, 0x6e, 0x2e, 0x68, 0x73, 0x65, 0x2e, 0x72, 0x75, 0x6e,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x72,
	0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x72, 0x75, 0x6e, 0x2e, 0x68, 0x73, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x22, 0x2a, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x2c, 0x0a, 0x11, 0x50, 0x75, 0x74, 0x49, 0x6e,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x43, 0x61, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x70, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6f, 0x70, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x22, 0x34, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x70, 0x70, 0x6f, 0x6e, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6f, 0x70, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x67, 0x61, 0x6d,
	0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x79, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x2b, 0x0a, 0x11, 0x6f, 0x70, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x5f,
	0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x6f, 0x70, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x05, 0x72, 0x6f, 0x6f,
	0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x72, 0x75, 0x6e, 0x2e, 0x68,
	0x73, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x05, 0x72, 0x6f, 0x6f,
	0x6d, 0x73, 0x22, 0x73, 0x0a, 0x0e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x67, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x34, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x75, 0x6e,
	0x2e, 0x68, 0x73, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x48, 0x00, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x08, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xfc, 0x03, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x6f,
	0x6f, 0x6d, 0x73, 0x42, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x2e, 0x72, 0x75, 0x6e, 0x2e,
	0x68, 0x73, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x42,
	0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x72,
	0x75, 0x6e, 0x2e, 0x68, 0x73, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f,
	0x6f, 0x6d, 0x42, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x44, 0x0a, 0x0a, 0x50, 0x75, 0x74, 0x49, 0x6e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x1e,
	0x2e, 0x72, 0x75, 0x6e, 0x2e, 0x68, 0x73, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x2e, 0x50, 0x75, 0x74,
	0x49, 0x6e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x41, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x46, 0x72, 0x6f, 0x6d, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3e, 0x0a, 0x07, 0x41, 0x64, 0x64,
	0x43, 0x61, 0x6c, 0x6c, 0x12, 0x1b, 0x2e, 0x72, 0x75, 0x6e, 0x2e, 0x68, 0x73, 0x65, 0x2e, 0x72,
	0x75, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x44, 0x0a, 0x0a, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x1e, 0x2e, 0x72, 0x75, 0x6e, 0x2e, 0x68, 0x73,
	0x65, 0x2e, 0x72, 0x75, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x40, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x2e, 0x72, 0x75,
	0x6e, 0x2e, 0x68, 0x73, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x43, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1b, 0x2e, 0x72, 0x75, 0x6e, 0x2e, 0x68, 0x73,
	0x65, 0x2e, 0x72, 0x75, 0x6e, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_server_proto_rawDescOnce sync.Once
	file_game_server_proto_rawDescData = file_game_server_proto_rawDesc
)

func file_game_server_proto_rawDescGZIP() []byte {
	file_game_server_proto_rawDescOnce.Do(func() {
		file_game_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_server_proto_rawDescData)
	})
	return file_game_server_proto_rawDescData
}

var file_game_server_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_game_server_proto_goTypes = []interface{}{
	(*GetRoomByCodeResponse)(nil), // 0: run.hse.run.GetRoomByCodeResponse
	(*GetRoomByCodeRequest)(nil),  // 1: run.hse.run.GetRoomByCodeRequest
	(*PutInQueueRequest)(nil),     // 2: run.hse.run.PutInQueueRequest
	(*AddCallRequest)(nil),        // 3: run.hse.run.AddCallRequest
	(*DeleteCallRequest)(nil),     // 4: run.hse.run.DeleteCallRequest
	(*SendTimeRequest)(nil),       // 5: run.hse.run.SendTimeRequest
	(*GameInfo)(nil),              // 6: run.hse.run.GameInfo
	(*StreamResponse)(nil),        // 7: run.hse.run.StreamResponse
	(*Room)(nil),                  // 8: run.hse.run.Room
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_game_server_proto_depIdxs = []int32{
	8,  // 0: run.hse.run.GetRoomByCodeResponse.rooms:type_name -> run.hse.run.Room
	8,  // 1: run.hse.run.GameInfo.rooms:type_name -> run.hse.run.Room
	6,  // 2: run.hse.run.StreamResponse.game_info:type_name -> run.hse.run.GameInfo
	1,  // 3: run.hse.run.GameService.GetRoomsByCode:input_type -> run.hse.run.GetRoomByCodeRequest
	2,  // 4: run.hse.run.GameService.PutInQueue:input_type -> run.hse.run.PutInQueueRequest
	9,  // 5: run.hse.run.GameService.DeleteFromQueue:input_type -> google.protobuf.Empty
	3,  // 6: run.hse.run.GameService.AddCall:input_type -> run.hse.run.AddCallRequest
	4,  // 7: run.hse.run.GameService.DeleteCall:input_type -> run.hse.run.DeleteCallRequest
	5,  // 8: run.hse.run.GameService.SendTime:input_type -> run.hse.run.SendTimeRequest
	9,  // 9: run.hse.run.GameService.StreamGame:input_type -> google.protobuf.Empty
	0,  // 10: run.hse.run.GameService.GetRoomsByCode:output_type -> run.hse.run.GetRoomByCodeResponse
	9,  // 11: run.hse.run.GameService.PutInQueue:output_type -> google.protobuf.Empty
	9,  // 12: run.hse.run.GameService.DeleteFromQueue:output_type -> google.protobuf.Empty
	9,  // 13: run.hse.run.GameService.AddCall:output_type -> google.protobuf.Empty
	9,  // 14: run.hse.run.GameService.DeleteCall:output_type -> google.protobuf.Empty
	9,  // 15: run.hse.run.GameService.SendTime:output_type -> google.protobuf.Empty
	7,  // 16: run.hse.run.GameService.StreamGame:output_type -> run.hse.run.StreamResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_game_server_proto_init() }
func file_game_server_proto_init() {
	if File_game_server_proto != nil {
		return
	}
	file_room_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_game_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomByCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomByCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutInQueueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_game_server_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*StreamResponse_GameResult)(nil),
		(*StreamResponse_GameInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_server_proto_goTypes,
		DependencyIndexes: file_game_server_proto_depIdxs,
		MessageInfos:      file_game_server_proto_msgTypes,
	}.Build()
	File_game_server_proto = out.File
	file_game_server_proto_rawDesc = nil
	file_game_server_proto_goTypes = nil
	file_game_server_proto_depIdxs = nil
}
